### ISSUE TITLE
I got this Error when I run ember server

### ISSUE THREAD

**Issue by meagon** [idcos/osinstall-ui#4]
components/common/io-ansi/ansi_up.js: line 8, col 7, 'VERSION' is defined but never used.
components/common/io-ansi/ansi_up.js: line 11, col 7, 'hasModule' is defined but never used.

and Many errors like this

```

2 errors

dashboard/vs-install/route.js: line 29, col 14, Missing semicolon.

1 error

services/api/network/service.js: line 53, col 21, Missing semicolon.

1 error

utils/file-uploader.js: line 7, col 12, '$' is not defined.

1 error

===== 39 JSHint Errors

```

**Comment by yunji-devin** [comment]
@meagon These are just a notice message, not a fatal error,please ignore it.
